export const IPC_CHANNELS = {
  GET_APP_INFO: "get-app-info",
  GET_LLM_CONFIG: "get-llm-config",
  SAVE_LLM_CONFIG: "save-llm-config",
  DELETE_LLM_CONFIG: "delete-llm-config",
  TEST_LLM_CONNECTION: "test-llm-connection",
  SIDECAR_STATUS: "sidecar:status",
  CHAT_SEND: "chat:send",
  CHAT_CREATE_CONVERSATION: "chat:create-conversation",
  CHAT_GET_CONVERSATIONS: "chat:get-conversations",
  CHAT_GET_MESSAGES: "chat:get-messages",
  CLASSROOMS_LIST: "classrooms:list",
  CLASSROOM_CREATE: "classrooms:create",
  CLASSROOM_UPDATE: "classrooms:update",
  CLASSROOM_DELETE: "classrooms:delete",
  STUDENTS_LIST_BY_CLASSROOM: "students:list-by-classroom",
  STUDENT_GET: "student:get",
  STUDENT_CREATE: "student:create",
  STUDENT_UPDATE: "student:update",
  STUDENT_DELETE: "student:delete",
  PROFILE_UPSERT: "profile:upsert",
  LEARNING_NOTES_LIST_BY_STUDENT: "learning-notes:list-by-student",
  LEARNING_NOTE_ADD: "learning-note:add",
  FEEDBACK_LIST_BY_WEEK: "feedback:list-by-week",
  FEEDBACK_LIST_BY_STUDENT: "feedback:list-by-student",
  FEEDBACK_UPSERT: "feedback:upsert",
  FEEDBACK_GENERATE_SUMMARY: "feedback:generate-summary",
  DOCUMENTS_LIST: "documents:list",
  DOCUMENT_GET: "document:get",
  DOCUMENT_SAVE_APPROVED: "document:save-approved",
  DOCUMENT_EXPORT_DOCX: "document:export-docx",
  OAUTH_START_OPENROUTER: "oauth:start-openrouter",
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
